/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as IndexImport } from './pages/index'
import { Route as dashboardDashboardLayoutImport } from './pages/(dashboard)/_dashboardLayout'
import { Route as dashboardDashboardLayoutAdminIndexImport } from './pages/(dashboard)/_dashboardLayout/admin/index'
import { Route as dashboardDashboardLayoutMenu1Menu11Import } from './pages/(dashboard)/_dashboardLayout/menu1/menu1-1'
import { Route as dashboardDashboardLayoutDashboardWorkbenchImport } from './pages/(dashboard)/_dashboardLayout/dashboard/workbench'
import { Route as dashboardDashboardLayoutDashboardUserImport } from './pages/(dashboard)/_dashboardLayout/dashboard/user'
import { Route as dashboardDashboardLayoutMenu1Menu12Menu122Import } from './pages/(dashboard)/_dashboardLayout/menu1/menu1-2/menu1-2-2'
import { Route as dashboardDashboardLayoutMenu1Menu12Menu121Import } from './pages/(dashboard)/_dashboardLayout/menu1/menu1-2/menu1-2-1'
import { Route as dashboardDashboardLayoutDashboardAdminChildrenImport } from './pages/(dashboard)/_dashboardLayout/dashboard/admin/children'

// Create Virtual Routes

const dashboardImport = createFileRoute('/(dashboard)')()
const AboutLazyImport = createFileRoute('/about')()
const BlogIndexLazyImport = createFileRoute('/blog/')()

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexLazyRoute = BlogIndexLazyImport.update({
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/blog/index.lazy').then((d) => d.Route))

const dashboardDashboardLayoutRoute = dashboardDashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardDashboardLayoutAdminIndexRoute =
  dashboardDashboardLayoutAdminIndexImport.update({
    path: '/admin/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

const dashboardDashboardLayoutMenu1Menu11Route =
  dashboardDashboardLayoutMenu1Menu11Import.update({
    path: '/menu1/menu1-1',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

const dashboardDashboardLayoutDashboardWorkbenchRoute =
  dashboardDashboardLayoutDashboardWorkbenchImport.update({
    path: '/dashboard/workbench',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

const dashboardDashboardLayoutDashboardUserRoute =
  dashboardDashboardLayoutDashboardUserImport.update({
    path: '/dashboard/user',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

const dashboardDashboardLayoutMenu1Menu12Menu122Route =
  dashboardDashboardLayoutMenu1Menu12Menu122Import.update({
    path: '/menu1/menu1-2/menu1-2-2',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

const dashboardDashboardLayoutMenu1Menu12Menu121Route =
  dashboardDashboardLayoutMenu1Menu12Menu121Import.update({
    path: '/menu1/menu1-2/menu1-2-1',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

const dashboardDashboardLayoutDashboardAdminChildrenRoute =
  dashboardDashboardLayoutDashboardAdminChildrenImport.update({
    path: '/dashboard/admin/children',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardDashboardLayoutImport
      parentRoute: typeof dashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_dashboardLayout/dashboard/user': {
      id: '/_dashboardLayout/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof dashboardDashboardLayoutDashboardUserImport
      parentRoute: typeof dashboardDashboardLayoutImport
    }
    '/(dashboard)/_dashboardLayout/dashboard/workbench': {
      id: '/_dashboardLayout/dashboard/workbench'
      path: '/dashboard/workbench'
      fullPath: '/dashboard/workbench'
      preLoaderRoute: typeof dashboardDashboardLayoutDashboardWorkbenchImport
      parentRoute: typeof dashboardDashboardLayoutImport
    }
    '/(dashboard)/_dashboardLayout/menu1/menu1-1': {
      id: '/_dashboardLayout/menu1/menu1-1'
      path: '/menu1/menu1-1'
      fullPath: '/menu1/menu1-1'
      preLoaderRoute: typeof dashboardDashboardLayoutMenu1Menu11Import
      parentRoute: typeof dashboardDashboardLayoutImport
    }
    '/(dashboard)/_dashboardLayout/admin/': {
      id: '/_dashboardLayout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof dashboardDashboardLayoutAdminIndexImport
      parentRoute: typeof dashboardDashboardLayoutImport
    }
    '/(dashboard)/_dashboardLayout/dashboard/admin/children': {
      id: '/_dashboardLayout/dashboard/admin/children'
      path: '/dashboard/admin/children'
      fullPath: '/dashboard/admin/children'
      preLoaderRoute: typeof dashboardDashboardLayoutDashboardAdminChildrenImport
      parentRoute: typeof dashboardDashboardLayoutImport
    }
    '/(dashboard)/_dashboardLayout/menu1/menu1-2/menu1-2-1': {
      id: '/_dashboardLayout/menu1/menu1-2/menu1-2-1'
      path: '/menu1/menu1-2/menu1-2-1'
      fullPath: '/menu1/menu1-2/menu1-2-1'
      preLoaderRoute: typeof dashboardDashboardLayoutMenu1Menu12Menu121Import
      parentRoute: typeof dashboardDashboardLayoutImport
    }
    '/(dashboard)/_dashboardLayout/menu1/menu1-2/menu1-2-2': {
      id: '/_dashboardLayout/menu1/menu1-2/menu1-2-2'
      path: '/menu1/menu1-2/menu1-2-2'
      fullPath: '/menu1/menu1-2/menu1-2-2'
      preLoaderRoute: typeof dashboardDashboardLayoutMenu1Menu12Menu122Import
      parentRoute: typeof dashboardDashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface dashboardDashboardLayoutRouteChildren {
  dashboardDashboardLayoutDashboardUserRoute: typeof dashboardDashboardLayoutDashboardUserRoute
  dashboardDashboardLayoutDashboardWorkbenchRoute: typeof dashboardDashboardLayoutDashboardWorkbenchRoute
  dashboardDashboardLayoutMenu1Menu11Route: typeof dashboardDashboardLayoutMenu1Menu11Route
  dashboardDashboardLayoutAdminIndexRoute: typeof dashboardDashboardLayoutAdminIndexRoute
  dashboardDashboardLayoutDashboardAdminChildrenRoute: typeof dashboardDashboardLayoutDashboardAdminChildrenRoute
  dashboardDashboardLayoutMenu1Menu12Menu121Route: typeof dashboardDashboardLayoutMenu1Menu12Menu121Route
  dashboardDashboardLayoutMenu1Menu12Menu122Route: typeof dashboardDashboardLayoutMenu1Menu12Menu122Route
}

const dashboardDashboardLayoutRouteChildren: dashboardDashboardLayoutRouteChildren =
  {
    dashboardDashboardLayoutDashboardUserRoute:
      dashboardDashboardLayoutDashboardUserRoute,
    dashboardDashboardLayoutDashboardWorkbenchRoute:
      dashboardDashboardLayoutDashboardWorkbenchRoute,
    dashboardDashboardLayoutMenu1Menu11Route:
      dashboardDashboardLayoutMenu1Menu11Route,
    dashboardDashboardLayoutAdminIndexRoute:
      dashboardDashboardLayoutAdminIndexRoute,
    dashboardDashboardLayoutDashboardAdminChildrenRoute:
      dashboardDashboardLayoutDashboardAdminChildrenRoute,
    dashboardDashboardLayoutMenu1Menu12Menu121Route:
      dashboardDashboardLayoutMenu1Menu12Menu121Route,
    dashboardDashboardLayoutMenu1Menu12Menu122Route:
      dashboardDashboardLayoutMenu1Menu12Menu122Route,
  }

const dashboardDashboardLayoutRouteWithChildren =
  dashboardDashboardLayoutRoute._addFileChildren(
    dashboardDashboardLayoutRouteChildren,
  )

interface dashboardRouteChildren {
  dashboardDashboardLayoutRoute: typeof dashboardDashboardLayoutRouteWithChildren
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardDashboardLayoutRoute: dashboardDashboardLayoutRouteWithChildren,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardDashboardLayoutRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/blog': typeof BlogIndexLazyRoute
  '/dashboard/user': typeof dashboardDashboardLayoutDashboardUserRoute
  '/dashboard/workbench': typeof dashboardDashboardLayoutDashboardWorkbenchRoute
  '/menu1/menu1-1': typeof dashboardDashboardLayoutMenu1Menu11Route
  '/admin': typeof dashboardDashboardLayoutAdminIndexRoute
  '/dashboard/admin/children': typeof dashboardDashboardLayoutDashboardAdminChildrenRoute
  '/menu1/menu1-2/menu1-2-1': typeof dashboardDashboardLayoutMenu1Menu12Menu121Route
  '/menu1/menu1-2/menu1-2-2': typeof dashboardDashboardLayoutMenu1Menu12Menu122Route
}

export interface FileRoutesByTo {
  '/': typeof dashboardDashboardLayoutRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/blog': typeof BlogIndexLazyRoute
  '/dashboard/user': typeof dashboardDashboardLayoutDashboardUserRoute
  '/dashboard/workbench': typeof dashboardDashboardLayoutDashboardWorkbenchRoute
  '/menu1/menu1-1': typeof dashboardDashboardLayoutMenu1Menu11Route
  '/admin': typeof dashboardDashboardLayoutAdminIndexRoute
  '/dashboard/admin/children': typeof dashboardDashboardLayoutDashboardAdminChildrenRoute
  '/menu1/menu1-2/menu1-2-1': typeof dashboardDashboardLayoutMenu1Menu12Menu121Route
  '/menu1/menu1-2/menu1-2-2': typeof dashboardDashboardLayoutMenu1Menu12Menu122Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof dashboardRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_dashboardLayout': typeof dashboardDashboardLayoutRouteWithChildren
  '/blog/': typeof BlogIndexLazyRoute
  '/_dashboardLayout/dashboard/user': typeof dashboardDashboardLayoutDashboardUserRoute
  '/_dashboardLayout/dashboard/workbench': typeof dashboardDashboardLayoutDashboardWorkbenchRoute
  '/_dashboardLayout/menu1/menu1-1': typeof dashboardDashboardLayoutMenu1Menu11Route
  '/_dashboardLayout/admin/': typeof dashboardDashboardLayoutAdminIndexRoute
  '/_dashboardLayout/dashboard/admin/children': typeof dashboardDashboardLayoutDashboardAdminChildrenRoute
  '/_dashboardLayout/menu1/menu1-2/menu1-2-1': typeof dashboardDashboardLayoutMenu1Menu12Menu121Route
  '/_dashboardLayout/menu1/menu1-2/menu1-2-2': typeof dashboardDashboardLayoutMenu1Menu12Menu122Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/dashboard/user'
    | '/dashboard/workbench'
    | '/menu1/menu1-1'
    | '/admin'
    | '/dashboard/admin/children'
    | '/menu1/menu1-2/menu1-2-1'
    | '/menu1/menu1-2/menu1-2-2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/dashboard/user'
    | '/dashboard/workbench'
    | '/menu1/menu1-1'
    | '/admin'
    | '/dashboard/admin/children'
    | '/menu1/menu1-2/menu1-2-1'
    | '/menu1/menu1-2/menu1-2-2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_dashboardLayout'
    | '/blog/'
    | '/_dashboardLayout/dashboard/user'
    | '/_dashboardLayout/dashboard/workbench'
    | '/_dashboardLayout/menu1/menu1-1'
    | '/_dashboardLayout/admin/'
    | '/_dashboardLayout/dashboard/admin/children'
    | '/_dashboardLayout/menu1/menu1-2/menu1-2-1'
    | '/_dashboardLayout/menu1/menu1-2/menu1-2-2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  dashboardRoute: typeof dashboardRouteWithChildren
  BlogIndexLazyRoute: typeof BlogIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  dashboardRoute: dashboardRouteWithChildren,
  BlogIndexLazyRoute: BlogIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/",
        "/blog/"
      ]
    },
    "/": {
      "filePath": "(dashboard)",
      "children": [
        "/_dashboardLayout"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_dashboardLayout": {
      "filePath": "(dashboard)/_dashboardLayout.tsx",
      "parent": "/",
      "children": [
        "/_dashboardLayout/dashboard/user",
        "/_dashboardLayout/dashboard/workbench",
        "/_dashboardLayout/menu1/menu1-1",
        "/_dashboardLayout/admin/",
        "/_dashboardLayout/dashboard/admin/children",
        "/_dashboardLayout/menu1/menu1-2/menu1-2-1",
        "/_dashboardLayout/menu1/menu1-2/menu1-2-2"
      ]
    },
    "/blog/": {
      "filePath": "blog/index.lazy.tsx"
    },
    "/_dashboardLayout/dashboard/user": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/user.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/workbench": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/workbench.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/menu1/menu1-1": {
      "filePath": "(dashboard)/_dashboardLayout/menu1/menu1-1.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/admin/": {
      "filePath": "(dashboard)/_dashboardLayout/admin/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/admin/children": {
      "filePath": "(dashboard)/_dashboardLayout/dashboard/admin/children.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/menu1/menu1-2/menu1-2-1": {
      "filePath": "(dashboard)/_dashboardLayout/menu1/menu1-2/menu1-2-1.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/menu1/menu1-2/menu1-2-2": {
      "filePath": "(dashboard)/_dashboardLayout/menu1/menu1-2/menu1-2-2.tsx",
      "parent": "/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
